sudo: true

addons:
  apt:
    packages:
    - sox
    - ffmpeg

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install -e ./

script:
    - python --version
    - py.test -vs --cov=claudio .

after_success:
    - coveralls
    - pip uninstall -y claudio

after_failure:
    - pip uninstall -y claudio
